 create table "Students"(
 
    "Id" integer NOT NULL unique GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name_en" text COLLATE pg_catalog."default",
    "Name_ru" text COLLATE pg_catalog."default",
    "Name_uz" text COLLATE pg_catalog."default",
    "IsDeleted" integer not null default 0,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL
 
 );




INSERT INTO Migrations (MigrationName, CreatedAt) VALUES ('20240501120100_Students', CURRENT_TIMESTAMP);